apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-nfs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - rw
    - no_root_squash
  nfs:
    path: /volume1/Kubernetes/
    server: 10.0.166.151
 